### PR TITLE
fix: FileExists panics w/o read permission

### LINKED ISSUE #171: FileExists panics w/o read permission
See https://github.com/romie-gr/romie/blob/f4f9b85971f907970588030f8344ce86542495bd/internal/utils/filesystem.go#L16-L21

there is no check for permissions, as a result the value of `info` variable is `nil`.
As a result, if you create a testcase where the path has not read permissions, then the final return statement https://github.com/romie-gr/romie/blob/f4f9b85971f907970588030f8344ce86542495bd/internal/utils/filesystem.go#L23 panics, because it's doing: `true == nil` or `false == nil`.

I added a testcase to verify this:

```go
    --- FAIL: TestFileExists/Returns_false_when_file_is_into_a_folder_without_read_permissions (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x111e1be]

goroutine 22 [running]:
testing.tRunner.func1.1(0x113b2a0, 0x1248820)
        /usr/local/go/src/testing/testing.go:1076 +0x30d
testing.tRunner.func1(0xc000082f00)
        /usr/local/go/src/testing/testing.go:1079 +0x41a
panic(0x113b2a0, 0x1248820)
        /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/romie-gr/romie/internal/utils.exists(0xc00009e090, 0x2a, 0x100000000, 0xc00004a748)
        /Users/drpaneas/gocode/src/github.com/romie-gr/romie/internal/utils/filesystem.go:23 +0x5e
github.com/romie-gr/romie/internal/utils.FileExists(...)
        /Users/drpaneas/gocode/src/github.com/romie-gr/romie/internal/utils/filesystem.go:33
github.com/romie-gr/romie/internal/utils.TestFileExists.func1(0xc000082f00)
        /Users/drpaneas/gocode/src/github.com/romie-gr/romie/internal/utils/filesystem_test.go:118 +0x45
testing.tRunner(0xc000082f00, 0xc000092510)
        /usr/local/go/src/testing/testing.go:1127 +0xef
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1178 +0x386
exit status 2
FAIL    github.com/romie-gr/romie/internal/utils        0.300s
```

I found this issue while I was working on the `CreateFile` card.

### PR DESCRIPTION
**Pull request by drpaneas**
Add permission check

Fixes #171

### CODE REVIEW

**Review by zoispag — APPROVED** [review]

**Review by zoispag — DISMISSED** [review]
Are you sure the second test case fails for the correct reason? Looks to me that it fails because file does not exist, not because of permissions.

**Comment by drpaneas** [comment]
> Are you sure the second test case fails for the correct reason? Looks to me that it fails because file does not exist, not because of permissions.

yes, in both cases it through a segfault and crashes.

File: internal/utils/filesystem_test.go [hunk 1]
```diff
@@ -85,6 +93,16 @@ func TestFileExists(t *testing.T) {
 			nonExistingFile,
 			false,
 		},
+		{
+			"Returns false when given file and its parent folder do not exist",
+			filepath.Join(nonExistingFolder, "missing-file.txt"),
+			false,
+		},
```
Comment (zoispag) [inline internal/utils/filesystem_test.go]: Isn't this scenario redundant?

Comment (drpaneas) [reply internal/utils/filesystem_test.go]: it triggers the part of the code where parent dir doesn't exist, so it has to create it. Otherwise you end up with 90% test coverage.

Comment (zoispag) [reply internal/utils/filesystem_test.go]: I don't get that. Do you mean as part of the `CreateFile` method? Because the `exists` method does not differentiate between files and directories. If the path does not exist, it will "fail".

Comment (zoispag) [reply internal/utils/filesystem_test.go]: For the sake of argument, I tried to split the 2 checks into 2 if statements.

```go
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false
		}

		if os.IsPermission(err) {
			return false
		}
	}
```

I get 100% coverage without the scenario: `Returns false when given file and its parent folder do not exist`

Comment (drpaneas) [reply internal/utils/filesystem_test.go]: Sorry my bad. I got confused between `file.go` and `filesystem.go`. This is obviously redundant, thanks for catching it.

**Review by zoispag — APPROVED** [review]

File: internal/utils/filesystem_test.go [hunk 2]
```diff
@@ -70,6 +74,10 @@ func ExampleFileExists() {
 }
 
 func TestFileExists(t *testing.T) {
+	if err := os.Mkdir(nonWritableDir, 0400); err != nil {
+		log.Fatalf("Cannot create non writable directory %q", nonWritableDir)
+	}
+
```
Comment (ge0r) [inline internal/utils/filesystem_test.go:80]: Does it make sense to `defer` here the `os.RemoveAll(nonWritableDir)` for visibility?

**Review by zoispag — APPROVED** [review]

**Review by ge0r — APPROVED** [review]

File: internal/utils/filesystem_test.go (hunk 2 above)
Comment (zoispag) [reply internal/utils/filesystem_test.go:80]: Hm. I like this idea. I didn't think about that, when I added the cleanup call to the ExtractTo test case. Defer being idiomatic go and not something I am used to it yet, I usually forget about it! 😇
